apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  template:
    spec:
      containers:
      - name: sleep-job
        image: alpine
        command: ["sleep", "200000"]
      restartPolicy: Never
  backoffLimit: 4