---
- hosts: k8s-cluster
  become: true
  tasks:
  - name: k8s reset
    shell: |
      kubeadm reset -f
      rm $HOME/.kube/config
      systemctl stop kubelet
      systemctl stop docker
      rm -rf /var/lib/cni/
      rm -rf /var/lib/kubelet/*
      rm -rf /etc/cni/
      ifconfig cni0 down
      ifconfig flannel.1 down
      ifconfig docker0 down
      ip link delete cni0
      ip link delete flannel.1
      ifconfig cni0 down
      brctl delbr cni0
      ifconfig flannel.1 down
      systemctl restart kubelet
      systemctl restart docker
      rm /usr/local/bin/kubectl
      rm -rf ~/.kube